services:
  - type: web
    name: pdfforge-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        poppler-utils \
        ghostscript \
        libreoffice \
        wkhtmltopdf \
        tesseract-ocr \
        unpaper \
        pngquant \
        && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
